# AppVeyor configuration for AppVeyor project "Egoboo external".
clone_depth: 1

# Build worker image (VM template)
image: Visual Studio 2017

platform:
    - x86
    - x64
configuration:
    - Debug
    - Release

install:
    # depth 32 should be enough.
    git submodule update --init --recursive --depth 32
    
# Package artifacts and push packaged artifacts.
after_build:
    - ps: |
        ./distribute -configuration ${env:configuration} -platform ${env:platform} -suffix ${env:suffix}
        Push-AppveyorArtifact "${env:APPVEYOR_BUILD_FOLDER}/${env:artifactFileName}" -FileName "${env:artifactFileName}" -DeploymentName "${env:artifactName}"

# Restore nuget packages and install dependencies.        
# Furthermore, the artifact name and the artifact file name are computed.
before_build:
    - nuget restore
    - ps: .\install-vsix-appveyor.ps1
    - ps: |
        $env:suffix = "nightly"
        $env:artifactName = "egoboo-$(${env:configuration}.ToLower())-$env:platform-$env:suffix"
        Write-Host "artifact name = $env:artifactName"
        $env:artifactFileName = "${env:artifactName}.zip"
        Write-Host "artifact file name = $env:artifactFileName"
build:
    parallel: true                  # enable MSBuild parallel builds
    project: external.sln           # path to Visual Studio solution or project

test_script:
    - ps: |
        $platform = $env:platform
        if ($platform -eq "Win32") { $platform = "x86" }

# if one matrix entry fails, all entries fails
# https://www.appveyor.com/docs/build-configuration#failing-strategy
matrix:
    fast_finish: true
     
notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/7743b26cbf1767e7b3a3
      on_build_success: true
      on_build_failure: true
